[pytest]
addopts = -v -s --alluredir=allure-results
markers =
    regression: Регрессионные тесты
    authorization: Тесты авторизации
    products: Тесты страницы продуктов
    item: Тесты страницы карточки товара
    cart: Тесты корзины
    sorting: Тесты сортировки
    e2e: End-to-end сценарии
    checkout: Тесты оформления заказа
    checkout_overview: Тесты страницы checkout overview
    checkout_complete: Тесты страницы checkout complete